Wrap 'error' and 'applicationIOE' with AtomicReference
Under high load it is possible that one thread makes the check for non-null and before the copy another thread to null-fy the member field.

SEVERE: Servlet.service() for servlet [plaintext] in context with path [] threw exception
java.lang.NullPointerException: Cannot throw exception because "ioe" is null
	at org.apache.coyote.http2.Http2UpgradeHandler.handleAppInitiatedIOException(Http2UpgradeHandler.java:797)
	at org.apache.coyote.http2.Http2AsyncUpgradeHandler.handleAsyncException(Http2AsyncUpgradeHandler.java:276)
	at org.apache.coyote.http2.Http2AsyncUpgradeHandler.writeWindowUpdate(Http2AsyncUpgradeHandler.java:252)
	at org.apache.coyote.http2.Stream$StreamInputBuffer.doRead(Stream.java:1088)
	at org.apache.coyote.Request.doRead(Request.java:555)
	at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:336)
	at org.apache.catalina.connector.InputBuffer.checkByteBufferEof(InputBuffer.java:632)
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:362)
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132)
	at org.apache.catalina.connector.Request.readPostBody(Request.java:3308)
	at org.apache.catalina.connector.Request.parseParameters(Request.java:3241)
	at org.apache.catalina.connector.Request.getParameter(Request.java:1124)
	at org.apache.catalina.connector.RequestFacade.getParameter(RequestFacade.java:381)
	at info.mgsolutions.tomcat.PlainTextServlet.doPost(PlainTextServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
  ...