Add missing public on constructor. Otherwise when using form based authentication: +++ java.lang.NoClassDefFoundError: org/apache/tomcat/util/http/NamesEnumerator         at org.apache.tomcat.util.http.MimeHeaders.names(MimeHeaders.java:201)         at org.apache.catalina.connector.Request.getHeaderNames(Request.java:1873)         at org.apache.catalina.authenticator.FormAuthenticator.saveRequest(FormAuthenticator.java:479) +++
git-svn-id: https://svn.apache.org/repos/asf/tomcat/trunk@640888 13f79535-47bb-0310-9956-ffa450edef68