Note that using SSLProtocol="TLSv1.1,TLSv1.2" requires native 1.1.32 or later. Running with 1.1.31 is OK as long as the new values are not used in configuration.
Using "TLSv1.1" with Tomcat Native 1.1.31 results in
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8443]]
Caused by: java.lang.Exception: Invalid Server SSL Protocol (error:00000000:lib(0):func(0):reason(0))
	at org.apache.tomcat.jni.SSLContext.make(Native Method)
	at org.apache.tomcat.util.net.AprEndpoint.bind(AprEndpoint.java:527)


git-svn-id: https://svn.apache.org/repos/asf/tomcat/trunk@1632975 13f79535-47bb-0310-9956-ffa450edef68