Revert "Update Hamcrest to 2.2"
This reverts commit d9434f7686667b87cce0aad5c1377551f90f79c0.

Revert temporarily the update because some tests have failed:

Testcase: initializationError took 0.001 sec
        Caused an ERROR
org/hamcrest/SelfDescribing
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        ...