Fixed test cases that errored due to path case sentsitivity on Windows
e.g. Testcase: testNestedJarGetURL took 2.628 sec
 FAILED
expected:<jar:war:file:/[e]:/Workspace/git/tomc...> but was:<jar:war:file:/[E]:/Workspace/git/tomc...>
junit.framework.AssertionFailedError: expected:<jar:war:file:/[e]:/Workspace/git/tomc...> but was:<jar:war:file:/[E]:/Workspace/git/tomc...>
 at org.apache.catalina.webresources.TestAbstractArchiveResource.testNestedJarGetURL(TestAbstractArchiveResource.java:51)

git-svn-id: https://svn.apache.org/repos/asf/tomcat/trunk@1842657 13f79535-47bb-0310-9956-ffa450edef68