Use newInstance() rather than newFactory(). The behaviour is identical and there are a couple of reasons to avoid newFactory() - it is deprecated in Java 9 onwards - it isn't present in Xerces so users over-riding the JRE XML implementation with Xerces will see NoSuchMethodError when they try to process JSPs (seen via $work)
git-svn-id: https://svn.apache.org/repos/asf/tomcat/tc8.5.x/trunk@1805778 13f79535-47bb-0310-9956-ffa450edef68